server:
  port: 8100

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users_test?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database: mysql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
